### ISSUE TITLE
Error running  the arrow projection with Rviz

### ISSUE THREAD

**Issue by Nowayoreal** [umhan35/arrow_projection#1]
Hello,
I tried to run the arrow projection via image-viewer and RViz but I got a blank dark screen and the error in the image attached.
Could it be because I didn't have a projector connected? Could just any projector work if that is the case?

I studied the 4 page publication as recommended, and in my simulation, I also used the ROS navigation stack (move_base packages, DWA etc).  Although, I am somehow intermediate  in ROS. However, I am wondering if there are some settings to do on my navigation stack packages apart from subscribing to the global path plan ROS topic?

Thank you for your time and in anticipation of your reply.

![Screenshot from 2022-04-02 22-06-41](https://user-images.githubusercontent.com/95521617/164995302-4dfe1256-396b-4d10-a28f-2a8cda641f3c.png)

**Comment by umhan35** [comment]
As shown in the error message, you need to install moveit and [jsk_rviz_plugins](https://wiki.ros.org/jsk_rviz_plugins). Otherwise, you can edit the rviz file to remove them.
